// Usage: node scripts/generate-env.js
// Reads .env and generates Angular environment files at src/environments
const fs = require('fs');
const path = require('path');
const dotenv = require('dotenv');

const root = path.resolve(__dirname, '..');
const envPath = path.join(root, '.env');
const outDir = path.join(root, 'src', 'environments');

if (!fs.existsSync(outDir)) {
  fs.mkdirSync(outDir, { recursive: true });
}

const result = dotenv.config({ path: envPath });
if (result.error) {
  console.warn('.env not found — generating environment files with defaults');
}

const API_BASE_URL = process.env.API_BASE_URL || 'http://localhost:8088';
// normalize login path to start with single slash
let AUTH_LOGIN_PATH = process.env.AUTH_LOGIN_PATH || '/api/auth/login';
if (!AUTH_LOGIN_PATH.startsWith('/')) AUTH_LOGIN_PATH = '/' + AUTH_LOGIN_PATH;

const TOKEN_STORAGE_KEY = process.env.TOKEN_STORAGE_KEY || 'jwt_token';

const envTemplate = (prod) => `// This file is auto-generated by scripts/generate-env.js
export const environment = {
  production: ${prod},
  apiBaseUrl: '${API_BASE_URL}',
  authLoginPath: '${AUTH_LOGIN_PATH}',
  tokenStorageKey: '${TOKEN_STORAGE_KEY}'
};
`;

fs.writeFileSync(path.join(outDir, 'environment.ts'), envTemplate(false));
fs.writeFileSync(path.join(outDir, 'environment.prod.ts'), envTemplate(true));

console.log('Wrote', path.join(outDir, 'environment.ts'));
console.log('Wrote', path.join(outDir, 'environment.prod.ts'));
