import * as z from 'zod';

export const pdfGenerationSchema = z.object({
  name: z.string().min(1, 'Name ist erforderlich'),
  datumStart: z.string().min(1, 'Startdatum ist erforderlich'),
  datumEnde: z.string().min(1, 'Enddatum ist erforderlich'),
  nummer: z.number().int().min(1, 'Nummer muss mindestens 1 sein'),
  ausbildungsjahr: z
    .string()
    .min(1, 'Ausbildungsjahr ist erforderlich'),
  ausbilderId: z.string().uuid('Bitte wählen Sie einen Ausbilder'),
  listEvery: z.string().optional(),
  // Montag
  mo_Sec_1: z.string().optional(),
  mo_1: z.string().optional(),
  mo_Time_1: z.string().optional(),
  mo_Sec_2: z.string().optional(),
  mo_Time_2: z.string().optional(),
  mo_2: z.string().optional(),
  mo_Sec_3: z.string().optional(),
  mo_Time_3: z.string().optional(),
  mo_3: z.string().optional(),
  mo_Sec_4: z.string().optional(),
  mo_Time_4: z.string().optional(),
  mo_4: z.string().optional(),
  mo_Sec_5: z.string().optional(),
  mo_Total: z.string().optional(),
  mo_Time_5: z.string().optional(),
  mo_5: z.string().optional(),
  // Dienstag
  tu_Sec_1: z.string().optional(),
  tu_1: z.string().optional(),
  tu_Time_1: z.string().optional(),
  tu_Sec_2: z.string().optional(),
  tu_2: z.string().optional(),
  tu_Time_2: z.string().optional(),
  tu_Sec_3: z.string().optional(),
  tu_3: z.string().optional(),
  tu_Time_3: z.string().optional(),
  tu_Sec_4: z.string().optional(),
  tu_4: z.string().optional(),
  tu_Time_4: z.string().optional(),
  tu_Sec_5: z.string().optional(),
  tu_Total: z.string().optional(),
  tu_5: z.string().optional(),
  tu_Time_5: z.string().optional(),
  // Mittwoch
  we_Sec_1: z.string().optional(),
  we_1: z.string().optional(),
  we_Time_1: z.string().optional(),
  we_Sec_2: z.string().optional(),
  we_2: z.string().optional(),
  we_Time_2: z.string().optional(),
  we_3: z.string().optional(),
  we_Time_3: z.string().optional(),
  we_Sec_3: z.string().optional(),
  we_Sec_4: z.string().optional(),
  we_4: z.string().optional(),
  we_Time_4: z.string().optional(),
  we_Sec_5: z.string().optional(),
  we_Total: z.string().optional(),
  we_5: z.string().optional(),
  we_Time_5: z.string().optional(),
  // Donnerstag
  th_Sec_1: z.string().optional(),
  th_Time_1: z.string().optional(),
  th_1: z.string().optional(),
  th_Sec_2: z.string().optional(),
  th_Time_2: z.string().optional(),
  th_2: z.string().optional(),
  th_3: z.string().optional(),
  th_Sec_3: z.string().optional(),
  th_Time_3: z.string().optional(),
  th_4: z.string().optional(),
  th_Time_4: z.string().optional(),
  th_Sec_4: z.string().optional(),
  th_Sec_5: z.string().optional(),
  th_5: z.string().optional(),
  th_Total: z.string().optional(),
  th_Time_5: z.string().optional(),
  // Freitag
  fr_1: z.string().optional(),
  fr_Sec_1: z.string().optional(),
  fr_Time_1: z.string().optional(),
  fr_2: z.string().optional(),
  fr_Sec_2: z.string().optional(),
  fr_Time_2: z.string().optional(),
  fr_3: z.string().optional(),
  fr_Sec_3: z.string().optional(),
  fr_Time_3: z.string().optional(),
  fr_4: z.string().optional(),
  fr_Time_4: z.string().optional(),
  fr_Sec_4: z.string().optional(),
  fr_Total: z.string().optional(),
  fr_5: z.string().optional(),
  fr_Sec_5: z.string().optional(),
  fr_Time_5: z.string().optional(),
  // Samstag
  sa_Sec_1: z.string().optional(),
  sa_1: z.string().optional(),
  sa_Time_1: z.string().optional(),
  sa_2: z.string().optional(),
  sa_Sec_2: z.string().optional(),
  sa_Time_2: z.string().optional(),
  sa_3: z.string().optional(),
  sa_Time_3: z.string().optional(),
  sa_Sec_3: z.string().optional(),
  sa_Total: z.string().optional(),
  // Sonntag
  su_1: z.string().optional(),
  su_Sec_1: z.string().optional(),
  su_Time_1: z.string().optional(),
  su_2: z.string().optional(),
  su_Sec_2: z.string().optional(),
  su_Time_2: z.string().optional(),
  su_Sec_3: z.string().optional(),
  su_3: z.string().optional(),
  su_Time_3: z.string().optional(),
  su_Total: z.string().optional(),
  gesamtstunden: z.string().optional(),
  bemerkung: z.string().optional(),
  datumAzubi: z.string().optional(),
  signaturAzubi: z.string().optional(),
  signaturAusbilder: z.string().optional(),
});

export type PdfGenerationFormValues = z.infer<
  typeof pdfGenerationSchema
>;

export interface Ausbilder {
  id: string;
  name: string;
  email: string;
  profileImageUrl: string | null;
}
