CREATE SEQUENCE IF NOT EXISTS password_reset_tokens_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE IF NOT EXISTS activity
(
    id          UUID NOT NULL,
    nachweis_id UUID NOT NULL,
    day         VARCHAR(255),
    slot        INTEGER,
    description VARCHAR(2000),
    hours       DECIMAL,
    section     VARCHAR(255),
    CONSTRAINT pk_activity PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS app_user
(
    id                              UUID         NOT NULL,
    username                        VARCHAR(255) NOT NULL,
    name                            VARCHAR(255) NOT NULL,
    ausbildungsjahr                 INTEGER,
    telefonnummer                   VARCHAR(255),
    team                            VARCHAR(255),
    password                        VARCHAR(255) NOT NULL,
    email                           VARCHAR(255),
    profile_image_url               VARCHAR(255),
    fehlgeschlagene_anmeldeversuche INTEGER DEFAULT 0,
    account_gesperrt_bis            TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_app_user PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS nachweis
(
    id                 UUID         NOT NULL,
    name               VARCHAR(255) NOT NULL,
    datum_start        date,
    datum_ende         date,
    nummer             INTEGER      NOT NULL,
    ausbildungsjahr    VARCHAR(255),
    status             VARCHAR(255),
    comment            VARCHAR(255),
    ausbilder_id       UUID,
    azubi_id           UUID,
    datum_azubi        date,
    signatur_azubi     VARCHAR(255),
    signatur_ausbilder VARCHAR(255),
    bemerkung          VARCHAR(255),
    CONSTRAINT pk_nachweis PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS nachweis_audit_log
(
    id            UUID                        NOT NULL,
    nachweis_id   UUID                        NOT NULL,
    aktion        VARCHAR(255)                NOT NULL,
    aktions_zeit  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    benutzer_name VARCHAR(255)                NOT NULL,
    alte_daten    TEXT,
    neue_daten    TEXT,
    CONSTRAINT pk_nachweis_audit_log PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS password_reset_tokens
(
    id          BIGINT                      NOT NULL,
    token       VARCHAR(255)                NOT NULL,
    user_id     UUID                        NOT NULL,
    expiry_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_password_reset_tokens PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS role_audit
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    action          VARCHAR(255)                            NOT NULL,
    target_username VARCHAR(255)                            NOT NULL,
    performed_by    VARCHAR(255)                            NOT NULL,
    performed_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    details         VARCHAR(2048),
    CONSTRAINT pk_role_audit PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS roles
(
    id   UUID NOT NULL,
    name VARCHAR(20),
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS todo
(
    id          UUID         NOT NULL,
    title       VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    status      VARCHAR(20),
    user_id     UUID         NOT NULL,
    CONSTRAINT pk_todo PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS user_roles
(
    role_id UUID NOT NULL,
    user_id UUID NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (role_id, user_id)
);

ALTER TABLE app_user
    ADD CONSTRAINT uc_app_user_email UNIQUE (email);

ALTER TABLE app_user
    ADD CONSTRAINT uc_app_user_username UNIQUE (username);

ALTER TABLE nachweis
    ADD CONSTRAINT uc_cd53a53016dd35514d9fe7145 UNIQUE (nummer, azubi_id);

ALTER TABLE password_reset_tokens
    ADD CONSTRAINT uc_password_reset_tokens_token UNIQUE (token);

ALTER TABLE password_reset_tokens
    ADD CONSTRAINT uc_password_reset_tokens_user UNIQUE (user_id);

ALTER TABLE activity
    ADD CONSTRAINT FK_ACTIVITY_ON_NACHWEIS FOREIGN KEY (nachweis_id) REFERENCES nachweis (id);

ALTER TABLE nachweis
    ADD CONSTRAINT FK_NACHWEIS_ON_AUSBILDER FOREIGN KEY (ausbilder_id) REFERENCES app_user (id);

ALTER TABLE nachweis
    ADD CONSTRAINT FK_NACHWEIS_ON_AZUBI FOREIGN KEY (azubi_id) REFERENCES app_user (id);

ALTER TABLE password_reset_tokens
    ADD CONSTRAINT FK_PASSWORD_RESET_TOKENS_ON_USER FOREIGN KEY (user_id) REFERENCES app_user (id);

ALTER TABLE todo
    ADD CONSTRAINT FK_TODO_ON_USER FOREIGN KEY (user_id) REFERENCES app_user (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_user FOREIGN KEY (user_id) REFERENCES app_user (id);