import type { Metadata } from 'next';
import './globals.css';
import { Providers } from './Providers';
import { ToastProvider } from './ToastProvider';
import { AuthNavbarWrapper } from '@/components/core/AuthNavbarWrapper';
import { SessionExpiredModal } from '@/components/SessionExpiredModal';
import FirefoxWarning from '@/components/FirefoxWarning';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-sans antialiased`}>
        <Providers>
          <ToastProvider>
            <FirefoxWarning />
            <AuthNavbarWrapper />
            <main className="pt-16">{children}</main>
            <SessionExpiredModal />
          </ToastProvider>
        </Providers>
      </body>
    </html>
  );
}
